CREATE TABLE IF NOT EXITS SALESMAN {
    SALESMAN_ID TEXT PRIMARY KEY,
    NAME TEXT,
    CITY TEXT,
    COMISSION TEXT
};
INSERT INTO SALESMAN (SALESMAN_ID, NAME, CITY, COMISSION) VALUES
    ("5001", "JAMES HOOG", "NEW YORK", "0.15"),
    ('5002', 'NIAL KNITE', 'PARIS', '0.13'),
    ('5003', 'PIT ALEX', 'LONDON', '0.11'),
    ('5004', 'MC LYON', 'PARIS', '0.14'),
    ('5005', 'PAUL ADAM', 'ROME', '0.13'),
    ('5006', 'LAUSON HEN', 'SAN JOSE', '0.12');

CREATE TABLE IF NOT EXITS CUSTOMER (
    CUSTOMER_ID TEXT,
    CUST_NAME TEXT PRIMARY KEY,
    CITY TEXT,
    GRADE TEXT,
    SALESMAN_ID TEXT
);
INSERT INTO CUSTOMER(CUSTOMER_ID, CUST_NAME, CITY, GRADE, SALESMAN_ID) VALUES
